module.exports = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    me: '/auth/me',
    password: '/auth/password',
  },
  healthProfile: {
    me: '/health-profile/me',
    summary: '/health-profile/me/summary',
    allergens: '/health-profile/me/allergens',
    restrictions: '/health-profile/me/restrictions',
    chronicDiseases: '/health-profile/me/chronic-diseases',
  },
  weightRecords: {
    base: '/weight-records',
    trend: '/weight-records/trend',
    byId: (id) => `/weight-records/${id}`,
  },
  healthGoalCycles: {
    base: '/health-goal-cycles',
    current: '/health-goal-cycles/current',
    byId: (id) => `/health-goal-cycles/${id}`,
    complete: (id) => `/health-goal-cycles/${id}/complete`,
    cancel: (id) => `/health-goal-cycles/${id}/cancel`,
    progress: (id) => `/health-goal-cycles/${id}/progress`,
  },
  ingredients: {
    base: '/ingredients',
    byId: (id) => `/ingredients/${id}`,
    pairings: (id) => `/ingredients/${id}/pairings`,
  },
  recipes: {
    base: '/recipes',
    byId: (id) => `/recipes/${id}`,
    favorite: (id) => `/recipes/${id}/favorite`,
    suitability: (id) => `/recipes/${id}/suitability`,
  },
  mealPlans: {
    generateDay: '/meal-plans/generate/day',
    day: '/meal-plans/day',
    replaceItem: (planId, itemId) => `/meal-plans/${planId}/items/${itemId}/replace`,
    replacementCandidates: (planId, itemId) => `/meal-plans/${planId}/items/${itemId}/replacement-candidates`,
    feedbackItem: (planId, itemId) => `/meal-plans/${planId}/items/${itemId}/feedback`,
    completion: (planId) => `/meal-plans/${planId}/completion`,
    shoppingList: (planId) => `/meal-plans/${planId}/shopping-list`,
  },
  mealRecords: {
    base: '/meal-records',
    fromRecipe: (recipeId) => `/meal-records/from-recipe/${recipeId}`,
    day: '/meal-records/day',
    byId: (id) => `/meal-records/${id}`,
  },
  nutrition: {
    today: '/nutrition/today',
    range: '/nutrition/range',
    gap: '/nutrition/gap',
    risks: '/nutrition/risks',
  },
  nutritionReports: {
    weekly: '/nutrition-reports/weekly',
    monthly: '/nutrition-reports/monthly',
    base: '/nutrition-reports',
    byId: (id) => `/nutrition-reports/${id}`,
  },
  aiRecipes: {
    parse: '/ai-recipes/parse',
    parseImage: '/ai-recipes/parse-image',
    byId: (id) => `/ai-recipes/${id}`,
    history: '/ai-recipes/history',
    confirm: (id) => `/ai-recipes/${id}/confirm`,
    toRecipe: (id) => `/ai-recipes/${id}/to-recipe`,
    toMealRecord: (id) => `/ai-recipes/${id}/to-meal-record`,
  },
  advisor: {
    chat: '/ai/advisor/chat',
    todayDiagnosis: '/ai/advisor/today-diagnosis',
    weekPoster: (planId) => `/ai/advisor/week-poster/${planId}`,
  },
  community: {
    postImages: '/community/post-images',
    posts: '/community/posts',
    postById: (id) => `/community/posts/${id}`,
    comments: (id) => `/community/posts/${id}/comments`,
    like: (id) => `/community/posts/${id}/like`,
    favorite: (id) => `/community/posts/${id}/favorite`,
  },
}
