export const ENDPOINTS = {
  auth: {
    register: '/auth/register',
    login: '/auth/login',
    me: '/auth/me',
    password: '/auth/password',
  },
  healthProfile: {
    me: '/health-profile/me',
    summary: '/health-profile/me/summary',
    allergens: '/health-profile/me/allergens',
    restrictions: '/health-profile/me/restrictions',
    chronicDiseases: '/health-profile/me/chronic-diseases',
  },
  weightRecords: {
    base: '/weight-records',
    trend: '/weight-records/trend',
    byId: (id) => `/weight-records/${id}`,
  },
  healthGoalCycles: {
    base: '/health-goal-cycles',
    current: '/health-goal-cycles/current',
    byId: (id) => `/health-goal-cycles/${id}`,
    complete: (id) => `/health-goal-cycles/${id}/complete`,
    cancel: (id) => `/health-goal-cycles/${id}/cancel`,
    progress: (id) => `/health-goal-cycles/${id}/progress`,
  },
  ingredients: {
    base: '/ingredients',
    byId: (id) => `/ingredients/${id}`,
    disable: (id) => `/ingredients/${id}/disable`,
    pairings: (id) => `/ingredients/${id}/pairings`,
  },
  recipes: {
    base: '/recipes',
    byId: (id) => `/recipes/${id}`,
    ingredients: (id) => `/recipes/${id}/ingredients`,
    nutritionCalculate: (id) => `/recipes/${id}/nutrition/calculate`,
    suitability: (id) => `/recipes/${id}/suitability`,
    suitabilityRecalculate: '/recipes/suitability/recalculate',
    favorite: (id) => `/recipes/${id}/favorite`,
  },
  mealPlans: {
    generateDay: '/meal-plans/generate/day',
    day: '/meal-plans/day',
    replacementCandidates: (planId, itemId) => `/meal-plans/${planId}/items/${itemId}/replacement-candidates`,
    replaceItem: (planId, itemId) => `/meal-plans/${planId}/items/${itemId}/replace`,
    replaceLogs: (planId) => `/meal-plans/${planId}/replace-logs`,
    feedbackItem: (planId, itemId) => `/meal-plans/${planId}/items/${itemId}/feedback`,
    feedback: (planId) => `/meal-plans/${planId}/feedback`,
    completion: (planId) => `/meal-plans/${planId}/completion`,
    toRecords: (planId) => `/meal-plans/${planId}/to-records`,
    shoppingList: (planId) => `/meal-plans/${planId}/shopping-list`,
  },
  aiAdvisor: {
    chat: '/ai/advisor/chat',
    todayDiagnosis: '/ai/advisor/today-diagnosis',
    weekPoster: (planId) => `/ai/advisor/week-poster/${planId}`,
  },
  mealRecords: {
    base: '/meal-records',
    fromRecipe: (recipeId) => `/meal-records/from-recipe/${recipeId}`,
    fromAiRecipe: (aiRecipeId) => `/meal-records/from-ai-recipe/${aiRecipeId}`,
    day: '/meal-records/day',
    byId: (id) => `/meal-records/${id}`,
  },
  nutrition: {
    today: '/nutrition/today',
    range: '/nutrition/range',
    gap: '/nutrition/gap',
    risks: '/nutrition/risks',
    recipe: (recipeId) => `/nutrition/recipes/${recipeId}`,
  },
  nutritionRiskRules: {
    base: '/nutrition-risk-rules',
    byId: (id) => `/nutrition-risk-rules/${id}`,
    status: (id) => `/nutrition-risk-rules/${id}/status`,
    evaluate: '/nutrition-risk-rules/evaluate',
  },
  nutritionReports: {
    weekly: '/nutrition-reports/weekly',
    monthly: '/nutrition-reports/monthly',
    base: '/nutrition-reports',
    byId: (id) => `/nutrition-reports/${id}`,
  },
  aiRecipes: {
    parse: '/ai-recipes/parse',
    parseImage: '/ai-recipes/parse-image',
    byId: (id) => `/ai-recipes/${id}`,
    history: '/ai-recipes/history',
    confirm: (id) => `/ai-recipes/${id}/confirm`,
    toRecipe: (id) => `/ai-recipes/${id}/to-recipe`,
    toMealRecord: (id) => `/ai-recipes/${id}/to-meal-record`,
  },
  community: {
    postImages: '/community/post-images',
    posts: '/community/posts',
    fromAiRecipe: (aiRecipeId) => `/community/posts/from-ai-recipe/${aiRecipeId}`,
    postById: (id) => `/community/posts/${id}`,
    comments: (id) => `/community/posts/${id}/comments`,
    like: (id) => `/community/posts/${id}/like`,
    favorite: (id) => `/community/posts/${id}/favorite`,
  },
  admin: {
    users: '/admin/users',
    disableUser: (id) => `/admin/users/${id}/disable`,
    reviewRecipe: (id) => `/admin/recipes/${id}/review`,
    reviewPost: (id) => `/admin/community/posts/${id}/review`,
    aiCallLogs: '/admin/ai-call-logs',
    nutritionRiskResults: '/admin/nutrition-risk-results',
    nutritionReportStatistics: '/admin/nutrition-reports/statistics',
    demoDataReset: '/admin/demo-data/reset',
  },
}
