export const DATA_SOURCE = {
  MOCK: 'mock',
  REAL: 'real',
}

export const MOCK_SCENARIO = {
  SUCCESS: 'success',
  EMPTY: 'empty',
  ERROR: 'error',
  TIMEOUT: 'timeout',
}

export const endpointDataSource = {
  'POST /auth/register': DATA_SOURCE.MOCK,
  'POST /auth/login': DATA_SOURCE.MOCK,
  'GET /auth/me': DATA_SOURCE.MOCK,
  'PUT /auth/password': DATA_SOURCE.MOCK,
  'GET /health-profile/me': DATA_SOURCE.MOCK,
  'PUT /health-profile/me': DATA_SOURCE.MOCK,
  'GET /health-profile/me/summary': DATA_SOURCE.MOCK,
  'PUT /health-profile/me/allergens': DATA_SOURCE.MOCK,
  'PUT /health-profile/me/restrictions': DATA_SOURCE.MOCK,
  'POST /health-goal-cycles': DATA_SOURCE.MOCK,
  'GET /health-goal-cycles/current': DATA_SOURCE.MOCK,
  'GET /health-goal-cycles': DATA_SOURCE.MOCK,
  'PUT /health-goal-cycles/{id}': DATA_SOURCE.MOCK,
  'PATCH /health-goal-cycles/{id}/complete': DATA_SOURCE.MOCK,
  'PATCH /health-goal-cycles/{id}/cancel': DATA_SOURCE.MOCK,
  'GET /health-goal-cycles/{id}/progress': DATA_SOURCE.MOCK,
  'GET /ingredients': DATA_SOURCE.MOCK,
  'GET /ingredients/{id}': DATA_SOURCE.MOCK,
  'POST /ingredients': DATA_SOURCE.MOCK,
  'PUT /ingredients/{id}': DATA_SOURCE.MOCK,
  'PATCH /ingredients/{id}/disable': DATA_SOURCE.MOCK,
  'GET /recipes': DATA_SOURCE.MOCK,
  'GET /recipes/{id}': DATA_SOURCE.MOCK,
  'POST /recipes': DATA_SOURCE.MOCK,
  'PUT /recipes/{id}': DATA_SOURCE.MOCK,
  'PUT /recipes/{id}/ingredients': DATA_SOURCE.MOCK,
  'POST /recipes/{id}/nutrition/calculate': DATA_SOURCE.MOCK,
  'GET /recipes/{id}/suitability': DATA_SOURCE.MOCK,
  'POST /recipes/suitability/recalculate': DATA_SOURCE.MOCK,
  'POST /recipes/{id}/favorite': DATA_SOURCE.MOCK,
  'DELETE /recipes/{id}/favorite': DATA_SOURCE.MOCK,
  'POST /meal-plans/generate/day': DATA_SOURCE.MOCK,
  'GET /meal-plans/day': DATA_SOURCE.MOCK,
  'GET /meal-plans/{planId}/items/{itemId}/replacement-candidates': DATA_SOURCE.MOCK,
  'PATCH /meal-plans/{planId}/items/{itemId}/replace': DATA_SOURCE.MOCK,
  'GET /meal-plans/{planId}/replace-logs': DATA_SOURCE.MOCK,
  'POST /meal-plans/{planId}/items/{itemId}/feedback': DATA_SOURCE.MOCK,
  'GET /meal-plans/{planId}/feedback': DATA_SOURCE.MOCK,
  'GET /meal-plans/{planId}/completion': DATA_SOURCE.MOCK,
  'POST /meal-plans/{planId}/to-records': DATA_SOURCE.MOCK,
  'POST /meal-records': DATA_SOURCE.MOCK,
  'POST /meal-records/from-recipe/{recipeId}': DATA_SOURCE.MOCK,
  'POST /meal-records/from-ai-recipe/{aiRecipeId}': DATA_SOURCE.MOCK,
  'GET /meal-records/day': DATA_SOURCE.MOCK,
  'DELETE /meal-records/{id}': DATA_SOURCE.MOCK,
  'GET /nutrition/today': DATA_SOURCE.MOCK,
  'GET /nutrition/range': DATA_SOURCE.MOCK,
  'GET /nutrition/gap': DATA_SOURCE.MOCK,
  'GET /nutrition/risks': DATA_SOURCE.MOCK,
  'GET /nutrition/recipes/{recipeId}': DATA_SOURCE.MOCK,
  'GET /nutrition-risk-rules': DATA_SOURCE.MOCK,
  'POST /nutrition-risk-rules': DATA_SOURCE.MOCK,
  'PUT /nutrition-risk-rules/{id}': DATA_SOURCE.MOCK,
  'PATCH /nutrition-risk-rules/{id}/status': DATA_SOURCE.MOCK,
  'POST /nutrition-risk-rules/evaluate': DATA_SOURCE.MOCK,
  'POST /nutrition-reports/weekly': DATA_SOURCE.MOCK,
  'POST /nutrition-reports/monthly': DATA_SOURCE.MOCK,
  'GET /nutrition-reports': DATA_SOURCE.MOCK,
  'GET /nutrition-reports/{id}': DATA_SOURCE.MOCK,
  'DELETE /nutrition-reports/{id}': DATA_SOURCE.MOCK,
  'POST /ai-recipes/parse': DATA_SOURCE.REAL,
  'POST /ai-recipes/parse-image': DATA_SOURCE.REAL,
  'GET /ai-recipes/{id}': DATA_SOURCE.MOCK,
  'GET /ai-recipes/history': DATA_SOURCE.MOCK,
  'PATCH /ai-recipes/{id}/confirm': DATA_SOURCE.MOCK,
  'POST /ai-recipes/{id}/to-recipe': DATA_SOURCE.MOCK,
  'POST /ai-recipes/{id}/to-meal-record': DATA_SOURCE.MOCK,
  'DELETE /ai-recipes/{id}': DATA_SOURCE.MOCK,
  'POST /community/posts': DATA_SOURCE.MOCK,
  'POST /community/posts/from-ai-recipe/{aiRecipeId}': DATA_SOURCE.MOCK,
  'GET /community/posts': DATA_SOURCE.MOCK,
  'GET /community/posts/{id}': DATA_SOURCE.MOCK,
  'POST /community/posts/{id}/comments': DATA_SOURCE.MOCK,
  'POST /community/posts/{id}/like': DATA_SOURCE.MOCK,
  'POST /community/posts/{id}/favorite': DATA_SOURCE.MOCK,
  'GET /admin/users': DATA_SOURCE.MOCK,
  'PATCH /admin/users/{id}/disable': DATA_SOURCE.MOCK,
  'PATCH /admin/recipes/{id}/review': DATA_SOURCE.MOCK,
  'PATCH /admin/community/posts/{id}/review': DATA_SOURCE.MOCK,
  'GET /admin/ai-call-logs': DATA_SOURCE.MOCK,
  'GET /admin/nutrition-risk-results': DATA_SOURCE.MOCK,
  'GET /admin/nutrition-reports/statistics': DATA_SOURCE.MOCK,
  'POST /admin/demo-data/reset': DATA_SOURCE.MOCK,
}

export const endpointScenario = {
  'POST /auth/login': MOCK_SCENARIO.SUCCESS,
  'GET /health-profile/me': MOCK_SCENARIO.SUCCESS,
  'GET /health-goal-cycles/current': MOCK_SCENARIO.SUCCESS,
  'GET /ingredients': MOCK_SCENARIO.SUCCESS,
  'GET /recipes': MOCK_SCENARIO.SUCCESS,
  'GET /recipes/{id}/suitability': MOCK_SCENARIO.SUCCESS,
  'POST /meal-plans/generate/day': MOCK_SCENARIO.SUCCESS,
  'GET /meal-plans/day': MOCK_SCENARIO.SUCCESS,
  'GET /meal-records/day': MOCK_SCENARIO.SUCCESS,
  'GET /nutrition/today': MOCK_SCENARIO.SUCCESS,
  'GET /nutrition/range': MOCK_SCENARIO.SUCCESS,
  'GET /nutrition/risks': MOCK_SCENARIO.SUCCESS,
  'GET /nutrition-reports': MOCK_SCENARIO.SUCCESS,
  'GET /ai-recipes/history': MOCK_SCENARIO.SUCCESS,
  'GET /community/posts': MOCK_SCENARIO.SUCCESS,
  'GET /admin/users': MOCK_SCENARIO.SUCCESS,
  'GET /admin/ai-call-logs': MOCK_SCENARIO.SUCCESS,
  'GET /admin/nutrition-risk-results': MOCK_SCENARIO.SUCCESS,
  'GET /admin/nutrition-reports/statistics': MOCK_SCENARIO.SUCCESS,
}
